version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web-app"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
