version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web-app"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0 # Only security updates
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0 # Only security updates
