#
# ~ Docker Compose Configuration ~
#
# Creates the development environment with the backend API, mock API, web app
# and Redis server
#
# Services are configured to run on the following ports:
#   - 4200: Angular frontend application
#   - 8000: FastAPI backend API
#   - 8001: Mock API providing only static iRacing data
#   - 6379: Redis server
#
# To run the application: docker-compose up
#

services:
  # Configure the backend API
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - PORT=8000

  # Configure the web app
  web-app:
    build:
      context: ./web-app
    volumes:
      - ./web-app:/usr/src/web-app
      - /usr/src/web-app/node_modules
    ports:
      - "4200:4200"

  # Configure the mock API
  mock-api:
    build:
      context: ./mock-api
    volumes:
      - ./mock-api:/usr/src/mock-api
      - /usr/src/mock-api/node_modules
    ports:
      - "8001:8001"
    environment:
      - PORT=8001

  # Configure the Redis server
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Configure Playwright e2e tests
  e2e:
    build:
      context: ./e2e
    volumes:
      - ./web-app:/usr/src/web-app
    ports:
      - "8080:8080"
    depends_on:
      - web-app
      - backend
    # TODO: Disabling for now
    profiles:
      - donotstart
